package practicaswing.swing.layouts;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Container;
import java.awt.FlowLayout;
import java.awt.GridLayout;
import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;

/**
 *
 * @author Fedra Macario
 */
public class Ejemplo04_FormularioUsuario extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Ejemplo04_FormularioUsuario.class.getName());
    private JTextField txtNombre, txtDni;
    
    
    public Ejemplo04_FormularioUsuario() {
        super("Sistema de Gestión - Añadir Usuario");
        setSize(500, 250);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setLocationRelativeTo(null);

        Container cp = getContentPane();
        cp.setLayout(new BorderLayout(15, 15));
        cp.setBackground(new Color(245, 235, 220)); 

        // --- PANEL DE DATOS (CENTRO) ---
        JPanel panelDatos = new JPanel(new GridLayout(3, 2, 10, 15));
        panelDatos.setBorder(BorderFactory.createTitledBorder("Información Personal"));
        panelDatos.setOpaque(false);

        panelDatos.add(new JLabel("Nombre Completo:"));
        txtNombre = new JTextField();
        panelDatos.add(txtNombre);

        panelDatos.add(new JLabel("DNI / Identificación:"));
        txtDni = new JTextField();
        panelDatos.add(txtDni);

        panelDatos.add(new JLabel("Fecha de Nacimiento:"));
        
        // Panel de fecha (FlowLayout interno)
        JPanel panelFecha = new JPanel(new FlowLayout(FlowLayout.LEFT, 5, 0));
        panelFecha.setOpaque(false);
        panelFecha.add(new JTextField(3)); // Día
        panelFecha.add(new JLabel("/"));
        panelFecha.add(new JTextField(3)); // Mes
        panelFecha.add(new JLabel("/"));
        panelFecha.add(new JTextField(5)); // Año
        panelDatos.add(panelFecha);

        cp.add(panelDatos, BorderLayout.CENTER);

        // --- PANEL DE BOTONES (SUR) ---
        JPanel panelBotones = new JPanel(new FlowLayout(FlowLayout.RIGHT));
        panelBotones.setBackground(new Color(210, 160, 130)); // Tono crepé naranja suave

        JButton btnAceptar = new JButton("Registrar Usuario");
        btnAceptar.setBackground(new Color(60, 100, 60)); // Verde éxito
        btnAceptar.setForeground(Color.WHITE);
        
        // MEJORA: Validación simple
        btnAceptar.addActionListener(e -> {
            if(txtNombre.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Por favor, ingresa un nombre.", "Error", JOptionPane.WARNING_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "Usuario " + txtNombre.getText() + " registrado con éxito.");
            }
        });

        JButton btnCancelar = new JButton("Cancelar");
        btnCancelar.addActionListener(e -> System.exit(0));

        panelBotones.add(btnAceptar);
        panelBotones.add(btnCancelar);

        cp.add(panelBotones, BorderLayout.SOUTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        new Ejemplo04_FormularioUsuario().setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
