package practicaswing.swing.layouts;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Container;
import java.awt.Font;
import java.awt.GridLayout;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.JTextField;

/**
 *
 * @author Fedra Macario
 */
public class Ejemplo03_GrillaCalculadora extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Ejemplo03_GrillaCalculadora.class.getName());
    private JTextField pantalla;

   
    public Ejemplo03_GrillaCalculadora() {
        super("Teclado Interactivo");
        setSize(300, 450);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setLocationRelativeTo(null);
        
        // Contenedor principal con BorderLayout
        Container cp = getContentPane();
        cp.setLayout(new BorderLayout(10, 10));
        cp.setBackground(new Color(160, 240, 230)); 

        // 1. MEJORA: Pantalla en el NORTE
        pantalla = new JTextField();
        pantalla.setEditable(false);
        pantalla.setFont(new Font("Monospaced", Font.BOLD, 24));
        pantalla.setHorizontalAlignment(JTextField.RIGHT);
        pantalla.setBackground(new Color(245, 235, 220)); 
        cp.add(pantalla, BorderLayout.NORTH);

        // 2. Panel de botones con GridLayout (4 filas, 3 columnas)
        JPanel panelBotones = new JPanel(new GridLayout(4, 3, 5, 5));
        panelBotones.setBackground(new Color(160, 240, 230));

        // Arreglo con los textos de los botones
        String[] etiquetas = {"1", "2", "3", "4", "5", "6", "7", "8", "9", "*", "0", "+"};

        for (String texto : etiquetas) {
            JButton boton = new JButton(texto);
            boton.setFont(new Font("SansSerif", Font.BOLD, 18));
            boton.setBackground(new Color(110, 105, 130));
            boton.setForeground(Color.WHITE);
            
            // Acción para que escriba en la pantalla
            boton.addActionListener(e -> pantalla.setText(pantalla.getText() + texto));
            
            panelBotones.add(boton);
        }

        cp.add(panelBotones, BorderLayout.CENTER);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        new Ejemplo03_GrillaCalculadora().setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
