
package practicaswing.swing.mvc.vista;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Container;
import java.awt.Font;
import javax.swing.BorderFactory;
import javax.swing.DefaultListModel;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JList;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTextField;
import javax.swing.ListSelectionModel;
import practicaswing.swing.mvc.modelo.Tarea;

/**
 *
 * @author Fedra Macario
 */
public class VentanaTareas extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaTareas.class.getName());
    private JList<Tarea> vistaLista;
    private JTextField txtNuevaTarea;
    private JButton btnAgregar;
    
   
    // La vista recibe el modelo por parámetro para poder mostrarlo
    public VentanaTareas(DefaultListModel<Tarea> modeloTareas) {
        super("Ejemplo 07: LISTA - Mis Tareas");
        setSize(400, 450);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setLocationRelativeTo(null);
        
        Container cp = getContentPane();
        cp.setLayout(new BorderLayout(10, 10));
        cp.setBackground(new Color(245, 235, 220)); 

        // Lista
        vistaLista = new JList<>(modeloTareas);
        vistaLista.setFont(new Font("SansSerif", Font.PLAIN, 16));
        vistaLista.setBackground(new Color(255, 250, 240)); 
        vistaLista.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        
        JScrollPane scrollPane = new JScrollPane(vistaLista);
        scrollPane.setBorder(BorderFactory.createTitledBorder("Doble clic para tachar/destachar"));
        scrollPane.setOpaque(false);
        cp.add(scrollPane, BorderLayout.CENTER);

        // Panel inferior
        JPanel panelEntrada = new JPanel(new BorderLayout(5, 5));
        panelEntrada.setOpaque(false);
        panelEntrada.setBorder(BorderFactory.createEmptyBorder(10, 10, 10, 10));

        txtNuevaTarea = new JTextField();
        txtNuevaTarea.setFont(new Font("SansSerif", Font.PLAIN, 14));
        panelEntrada.add(txtNuevaTarea, BorderLayout.CENTER);

        btnAgregar = new JButton("Agregar");
        btnAgregar.setBackground(new Color(210, 105, 30)); 
        btnAgregar.setForeground(Color.WHITE);
        btnAgregar.setFont(new Font("SansSerif", Font.BOLD, 12));
        panelEntrada.add(btnAgregar, BorderLayout.EAST);
        
        cp.add(panelEntrada, BorderLayout.SOUTH);
    }

    // --- GETTERS PARA EL CONTROLADOR ---
    public JButton getBtnAgregar() { return btnAgregar; }
    public JTextField getTxtNuevaTarea() { return txtNuevaTarea; }
    public JList<Tarea> getVistaLista() { return vistaLista; }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
