
package practicaswing.swing.graficos;

import java.awt.BasicStroke;
import java.awt.Color;
import java.awt.Container;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import javax.swing.JFrame;
import javax.swing.JPanel;

/**
 *
 * @author Fedra Macario
 */
public class Ejemplo06_DibujoPersonalizado extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Ejemplo06_DibujoPersonalizado.class.getName());

  
    public Ejemplo06_DibujoPersonalizado() {
        super("Ejemplo 06: Bandera Argentina");
        setSize(600, 400); // Proporción más rectangular para la bandera
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setLocationRelativeTo(null);

        // Agrega panel personalizado (el lienzo donde pinta)
        Container cp = getContentPane();
        cp.add(new PanelBandera());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        new Ejemplo06_DibujoPersonalizado().setVisible(true);
    }
    
    // Clase interna para el panel de dibujo
    class PanelBandera extends JPanel {

        @Override
        protected void paintComponent(Graphics g) {
            // Siempre hay que llamar al super.paintComponent(g) primero
            super.paintComponent(g); 

            // Convertimos a Graphics2D para que los bordes se vean suaves y sin píxeles marcados
            Graphics2D g2d = (Graphics2D) g;
            g2d.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);

            // Obtenemos el ancho y alto actual de la ventana
            int ancho = getWidth();
            int alto = getHeight();

            // Calculamos el alto de cada franja (un tercio del total)
            int altoFranja = alto / 3;

            // 1. DIBUJAMOS LAS TRES FRANJAS
            Color celesteOficial = new Color(116, 172, 223); // RGB del celeste

            // Franja superior (Celeste)
            g2d.setColor(celesteOficial);
            g2d.fillRect(0, 0, ancho, altoFranja);

            // Franja central (Blanca)
            g2d.setColor(Color.WHITE);
            g2d.fillRect(0, altoFranja, ancho, altoFranja);

            // Franja inferior (Celeste)
            g2d.setColor(celesteOficial);
            g2d.fillRect(0, altoFranja * 2, ancho, alto - (altoFranja * 2));

            // 2. DIBUJAMOS EL SOL DE MAYO
            Color amarilloSol = new Color(246, 180, 14); // RGB del sol
            g2d.setColor(amarilloSol);

            int diametroSol = altoFranja - 20; // Un poco más chico que la franja blanca
            int centroX = ancho / 2;
            int centroY = alto / 2;

            // --- LOS RAYOS DEL SOL ---
            // Usamos la lógica trigonométrica para hacer los rayos
            int largoRayo = diametroSol / 2 + 15; // Qué tan lejos llega la punta del rayo

            for (double d = 0; d < 2 * Math.PI; d += 0.2) {
                int xRayo = (int) (centroX + largoRayo * Math.cos(d));
                int yRayo = (int) (centroY + largoRayo * Math.sin(d));

                // Dibujamos el rayo desde el centro hacia afuera
                g2d.setStroke(new BasicStroke(3)); // Hacemos la línea más gruesa
                g2d.drawLine(centroX, centroY, xRayo, yRayo);
            }

            // --- LA CARA DEL SOL (Círculo central) ---
            // Dibujamos el círculo del sol relleno POR ENCIMA de las líneas de los rayos
            int xSol = centroX - (diametroSol / 2);
            int ySol = centroY - (diametroSol / 2);
            g2d.fillOval(xSol, ySol, diametroSol, diametroSol);

            // Opcional: Le hacemos un borde sutil al sol usando drawOval
            g2d.setColor(new Color(200, 120, 0)); // Naranja oscuro
            g2d.setStroke(new BasicStroke(1));
            g2d.drawOval(xSol, ySol, diametroSol, diametroSol);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
