
package practicaswing.swing.eventos;

import java.awt.Color;
import java.awt.Container;
import java.awt.FlowLayout;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Fedra Macario
 */
public class Ejemplo05_ManejoEventos extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Ejemplo05_ManejoEventos.class.getName());
    private JTextField cuadroTexto;
    private JButton botonSaludo;
    
    
    public Ejemplo05_ManejoEventos() {
        super("Ejemplo 05: Eventos de Teclado y Mouse");
        setSize(400, 170);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setLocationRelativeTo(null);
        
        Container cp = getContentPane();
        cp.setLayout(new FlowLayout(FlowLayout.CENTER, 15, 30));
        cp.setBackground(new Color(245, 235, 220)); 

        cp.add(new JLabel("Ingresá tu nombre:"));
        
        cuadroTexto = new JTextField(15);
        cp.add(cuadroTexto);
        
        botonSaludo = new JButton("Saludar");
        botonSaludo.setBackground(new Color(60, 100, 60)); 
        botonSaludo.setForeground(Color.WHITE);
        cp.add(botonSaludo);

        // Evento 1: Clic con el Mouse en el botón
        botonSaludo.addActionListener(e -> saludar());

        // MEJORA - Evento 2: Presionar "Enter" en el campo de texto
        cuadroTexto.addKeyListener(new KeyAdapter() {
            @Override
            public void keyPressed(KeyEvent e) {
                if (e.getKeyCode() == KeyEvent.VK_ENTER) {
                    saludar();
                }
            }
        });
    }
    
    // Método auxiliar para no repetir código en los dos eventos
    private void saludar() {
        String nombre = cuadroTexto.getText().trim();
        if (nombre.isEmpty()) {
            JOptionPane.showMessageDialog(this, "¡Epa! No escribiste nada.", "Aviso", JOptionPane.WARNING_MESSAGE);
        } else {
            // Cuadro de diálogo predefinido
            JOptionPane.showMessageDialog(this, "¡Hola, " + nombre + "! Qué bueno verte por acá.", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
            cuadroTexto.setText(""); // Limpiamos el campo después de saludar
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        new Ejemplo05_ManejoEventos().setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
